# Generated by Django 5.2.6 on 2025-09-20 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_registeredusers_registereduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='password',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
