# Generated by Django 5.2.6 on 2025-09-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_registereduser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='financing_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='investment_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='previous_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='reporting_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
