# Generated by Django 5.2.6 on 2025-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_registereduser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
