# Generated by Django 5.2.6 on 2025-09-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_startup_financing_flow_startup_investment_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='current_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
