# Generated by Django 5.2.6 on 2025-09-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_startup_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='label',
        ),
    ]
