# Generated by Django 5.2.6 on 2025-09-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_startup_label'),
        ('core', '0005_startup_current_revenue'),
    ]

    operations = [
    ]
