# Generated by Django 5.2.6 on 2025-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250928_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='is_deck_builder',
            field=models.BooleanField(default=False),
        ),
    ]
