# Generated by Django 5.2.6 on 2025-10-21 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_startup_is_deck_builder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='core.registereduser'),
        ),
    ]
