# Generated by Django 5.2.6 on 2025-10-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_startup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='funding_usage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
