# Generated by Django 5.2.6 on 2025-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_startup_funding_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='current_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assets that can be converted to cash within one year', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='current_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Debts due within one year', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='ebit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earnings Before Interest and Taxes', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='retained_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Accumulated retained earnings from prior periods', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='time_between_periods',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of years between previous and current revenue (e.g., 1.0 for annual)', max_digits=5, null=True),
        ),
    ]
