# Generated by Django 5.2.6 on 2025-11-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_startup_current_assets_startup_current_liabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current market valuation of the company', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='expected_future_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected future valuation at target date', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='years_to_future_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of years until expected future valuation is reached', max_digits=5, null=True),
        ),
    ]
