# Generated by Django 5.2.6 on 2025-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_startup_contact_email_startup_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founder_linkedin',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founder_name',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founder_title',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='year_founded',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='founder_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='founder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='founder_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
