# Generated by Django 5.2.6 on 2025-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_startupcomparison_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketanalysis',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='projected_revenue_final_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='valuation_multiple',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='years_to_projection',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
