# Generated by Django 5.2.6 on 2025-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_marketanalysis_current_valuation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprojection',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='financialprojection',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='financialprojection',
            name='year',
        ),
        migrations.RemoveField(
            model_name='marketanalysis',
            name='current_valuation',
        ),
        migrations.RemoveField(
            model_name='marketanalysis',
            name='projected_revenue_final_year',
        ),
        migrations.RemoveField(
            model_name='marketanalysis',
            name='valuation_multiple',
        ),
        migrations.RemoveField(
            model_name='marketanalysis',
            name='years_to_projection',
        ),
        migrations.AddField(
            model_name='financialprojection',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financialprojection',
            name='projected_revenue_final_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financialprojection',
            name='valuation_multiple',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='financialprojection',
            name='years_to_projection',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
