# Generated by Django 5.2.6 on 2026-01-08 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sync_deck_financials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='is_deck_builder',
        ),
        migrations.AddField(
            model_name='startup',
            name='additional_founders',
            field=models.TextField(blank=True, help_text='JSON array of founder objects', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='advisors',
            field=models.TextField(blank=True, help_text='JSON array of advisor objects', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='awards_and_recognition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='business_model_type',
            field=models.CharField(blank=True, help_text='e.g., SaaS, Marketplace, Transaction Fee, Hardware', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='cac',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer Acquisition Cost', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='capital_raised_to_date',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='company_stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('early_revenue', 'Early Revenue'), ('growth', 'Growth'), ('scale', 'Scale')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='competitive_advantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='competitors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='current_mrr_arr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly/Annual Recurring Revenue', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='current_round_type',
            field=models.CharField(blank=True, choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C+')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='data_room_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='demo_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='expected_runway_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='financial_projections',
            field=models.TextField(blank=True, help_text='JSON array of yearly projections', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_history',
            field=models.TextField(blank=True, help_text='JSON array of past rounds', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='go_to_market_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='gross_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='headquarters',
            field=models.CharField(blank=True, help_text='City, Country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='how_it_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='impact_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='intellectual_property',
            field=models.TextField(blank=True, help_text='Patents, proprietary tech', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='investor_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='key_assumptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='key_features',
            field=models.TextField(blank=True, help_text='JSON array or bullet points', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='key_partnerships',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='key_team_members',
            field=models.TextField(blank=True, help_text='JSON array of team member objects', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='key_traction_metrics',
            field=models.TextField(blank=True, help_text='GMV, MAU, retention, churn, NPS, etc.', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='startup_logos/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='ltv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lifetime Value', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='major_milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_size_sam',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serviceable Addressable Market', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_size_tam',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Addressable Market', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='notable_customers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='one_pager_pdf',
            field=models.FileField(blank=True, null=True, upload_to='one_pagers/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='operational_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='paid_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='pitch_deck_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='pitch_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='preferred_check_size_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='preferred_check_size_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='pricing_example',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='primary_market',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='product_status',
            field=models.CharField(blank=True, choices=[('prototype', 'Prototype'), ('beta', 'Beta'), ('live', 'Live'), ('revenue_generating', 'Revenue Generating')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='regulatory_status',
            field=models.TextField(blank=True, help_text='Licenses, compliance status', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='revenue_streams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='sdg_alignment',
            field=models.TextField(blank=True, help_text='Sustainable Development Goals alignment', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='solution_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='supported_platforms',
            field=models.CharField(blank=True, help_text='e.g., Web, iOS, Android', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='target_customer_segments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='target_geography',
            field=models.CharField(blank=True, help_text='e.g., PH, SEA, Global', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='target_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='team_size',
            field=models.IntegerField(blank=True, help_text='Number of full-time/part-time staff', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='total_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='ebit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='expected_future_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='retained_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='source_deck',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Original deck reference for migration purposes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_startups', to='core.deck'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='time_between_periods',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='years_to_future_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['company_name'], name='core_startu_company_b00dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['industry'], name='core_startu_industr_0a64d3_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['company_stage'], name='core_startu_company_659732_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['current_round_type'], name='core_startu_current_4e7007_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['-created_at'], name='core_startu_created_e56f43_idx'),
        ),
    ]
